version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4560-4576:4560-4576'
      - '8082:8080'
    environment:
      - SERVICES=sqs
    volumes:
      - './.localstack:/tmp/localstack/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
  aws-client:
    image: mesosphere/aws-cli:1.14.5
    volumes:
      - './scripts:/project/scripts'
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-central-1
    entrypoint: '/project/scripts/setup.sh'
